export default {
  'auto-launch': false,
  enableJSON_API: true,
  miniUseScrollVolume: false,
  minToTray: true,
  nativeFrame: (process.platform !== 'win32'),
  savePage: true,
  scrollLyrics: true,
  startMinimized: false,
  theme: false,
  themeColor: '#2196F3',
  themeType: 'FULL',
  themeTypeShouldTrackSystem: false,
  preventDisplaySleep: false,
  enableWin10MediaService: false,
  enableWin10MediaServiceTrackInfo: true,
  lastFMMapThumbToHeart: true,
  service: 'google-play-music',
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0',
  spoofUserAgent: true,
};
