export default {
  'auto-launch': false,
  enableJSON_API: true,
  miniUseScrollVolume: false,
  minToTray: true,
  nativeFrame: (process.platform !== 'win32'),
  savePage: true,
  scrollLyrics: true,
  startMinimized: false,
  theme: false,
  themeColor: '#2196F3',
  themeType: 'FULL',
  themeTypeShouldTrackSystem: false,
  preventDisplaySleep: false,
  enableWin10MediaService: false,
  enableWin10MediaServiceTrackInfo: true,
  lastFMMapThumbToHeart: true,
  service: 'google-play-music',
  spoofedUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
  spoofUserAgent: true,
};
