export default {
  'auto-launch': false,
  enableJSON_API: true,
  miniUseScrollVolume: false,
  minToTray: true,
  nativeFrame: (process.platform !== 'win32'),
  savePage: true,
  scrollLyrics: true,
  startMinimized: false,
  theme: false,
  themeColor: '#2196F3',
  themeType: 'FULL',
  themeTypeShouldTrackSystem: false,
  preventDisplaySleep: false,
  enableWin10MediaService: false,
  enableWin10MediaServiceTrackInfo: true,
  lastFMMapThumbToHeart: true,
  service: 'google-play-music',
  spoofUserAgent: true,
  viewYTMSwitch: true,
};
