name: google-play-music-desktop-player
version: '4.0.4'
summary: Standalone player for Google Play Music
description: |
  This Google Play Music player provides desktop integration - with music
  hotkeys and the sound indicator via an MPRIS interface, the abiliy to use
  custom colours and load custom themes, a remote-control interface, and
  lower resource consumption than a full-blown browser tab.
  .
  This is *not* an official Google project.
grade: stable
confinement: strict

apps:
  google-play-music-desktop-player:
    command: desktop-launch '$SNAP/google-play-music-desktop-player/Google\ Play\ Music\ Desktop\ Player'
    plugs:
      - pulseaudio
      - x11
      - opengl
      - browser-support
      - network
      - network-bind
      - process-control
      - unity7
      - gsettings
    slots:
      - mpris

parts:
  gpmdp-indicator-gtk2:
    plugin: autotools
    source: lp:libappindicator
    build-packages:
      - at-spi2-core
      - gobject-introspection
      - intltool
      - libdbus-glib-1-dev
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libindicator-dev
      - python-all-dev
      - python-gtk2-dev
      - valac
      - gnome-common
      - gtk-doc-tools
      # #Mono support
      - cli-common-dev # [!arm64 !ppc64el]
      - libnunit-cil-dev # [!arm64 !ppc64el]
      - mono-devel # [!arm64 !ppc64el]
      - gtk-sharp2-gapi # [!arm64 !ppc64el]
      - libgtk2.0-cil-dev # [!arm64 !ppc64el]
    configflags:
      - --disable-gtk-doc
      - --prefix=/usr
      - --with-gtk=2
      - --enable-gtk-doc=no
      - --enable-gtk-doc-html=no
      - --disable-tests
      - --disable-mono-test
    snap:
      - ./**/lib*.so.*
      - ./**/*.typelib
      - ./**/python2.7/**/appindicator
      - ./**/lib/cli
      - ./**/lib/mono

  google-play-music-desktop-player:
    plugin: gulp
    node-engine: 7.2.1
    source: .
    source-type: git
    gulp-tasks:
      - package:linux:64
    build-packages:
      - libavahi-compat-libdnssd-dev
      - libdbus-1-dev
      - libx11-dev
      - libexpat1-dev
      - libnotify-dev
    stage-packages:
      - libnss3
      - ca-certificates
      - libasound2-data
      - libasound2-plugins
      - libnotify4
    after:
      - desktop-gtk2
      - gpmdp-indicator-gtk2
    organize:
      '../build/dist/Google Play Music Desktop Player-linux-x64': google-play-music-desktop-player
