//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google_Play_Music.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Google_Play_Music.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string api_key {
            get {
                return ResourceManager.GetString("api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string api_secret {
            get {
                return ResourceManager.GetString("api_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var scrobbleTimer;
        ///
        ///window.GPM.on(&apos;change:song&apos;, function onSongChange(song) {
        ///    clearTimeout(scrobbleTimer);
        ///    csharpinterface.songChangeEvent(song.title, song.album, song.artist, song.art);
        ///    scrobbleTimer = setTimeout(function scrobbleTimer(songStart) {
        ///        console.info(&apos;send scrobble&apos;);
        ///        csharpinterface.songScrobbleRequest(song.title, song.artist, song.album, songStart);
        ///        console.info(song.title, song.artist, song.album, songStart);
        ///    }.bind(this, Math.floor(Date.now() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string custom_interface {
            get {
                return ResourceManager.GetString("custom_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require==&quot;function&quot;&amp;&amp;require;if(!u&amp;&amp;a)return a(o,!0);if(i)return i(o,!0);var f=new Error(&quot;Cannot find module &apos;&quot;+o+&quot;&apos;&quot;);throw f.code=&quot;MODULE_NOT_FOUND&quot;,f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require==&quot;function&quot;&amp;&amp;require;for(var o=0;o&lt;r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){window.GMusic=require(&quot;./main&quot;)} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gmusic_min {
            get {
                return ResourceManager.GetString("gmusic_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;use strict&quot;;function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError(&quot;Cannot call a class as a function&quot;)}var _createClass=function(){function a(a,b){for(var c=0;c&lt;b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1,d.configurable=!0,&quot;value&quot;in d&amp;&amp;(d.writable=!0),Object.defineProperty(a,d.key,d)}}return function(b,c,d){return c&amp;&amp;a(b.prototype,c),d&amp;&amp;a(b,d),b}}();!function a(b,c,d){function e(g,h){if(!c[g]){if(!b[g]){var i=&quot;function&quot;==typeof require&amp;&amp;require;if(!h&amp;&amp;i)return i(g,!0);if(f)retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gmusic_mini_player_min {
            get {
                return ResourceManager.GetString("gmusic_mini_player_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;use strict&quot;;function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError(&quot;Cannot call a class as a function&quot;)}function _typeof(a){return a&amp;&amp;&quot;undefined&quot;!=typeof Symbol&amp;&amp;a.constructor===Symbol?&quot;symbol&quot;:typeof a}var _createClass=function(){function a(a,b){for(var c=0;c&lt;b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1,d.configurable=!0,&quot;value&quot;in d&amp;&amp;(d.writable=!0),Object.defineProperty(a,d.key,d)}}return function(b,c,d){return c&amp;&amp;a(b.prototype,c),d&amp;&amp;a(b,d),b}}();!function a(b,c,d){function e(g, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gmusic_theme_min {
            get {
                return ResourceManager.GetString("gmusic_theme_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NextTrack {
            get {
                object obj = ResourceManager.GetObject("NextTrack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PrevTrack {
            get {
                object obj = ResourceManager.GetObject("PrevTrack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashDark {
            get {
                object obj = ResourceManager.GetObject("SplashDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
